server:
  port: 8082

spring:
  application:
    name: ORDER-HANDLER-SERVICE

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URI:http://auth-server:9000}

      client:
        registration:
          client-internal:
              client-id: ecommerce-client
              client-secret: ecommerce-secret
              authorization-grant-type: client_credentials
              scope: read,write,internal
              provider: cusom-auth
        provider:
          cusom-auth:
            issuer-uri: ${AUTHORIZATION_SERVER_URI:http://auth-server:9000}

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
