server:
  port: 8083

spring:
  application:
    name: PAYMENT-SERVICE
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost:5432}/microservice-ecommerce?schema=payment_schema
    username: postgres
    password: MohammadN@sr13804804

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - com.nasr.paymentservice.exception.ExternalServiceException
    instances:
      orderService:
        baseConfig: default
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always