server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost:5432}/microservice-ecommerce?schema=order_schema
    username: postgres
    password: MohammadN@sr13804804

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
