server:
  port: 8080
spring:
  application:
    name: PRODUCT-SERVICE
  r2dbc:
    username: postgres
    password: MohammadN@sr13804804
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/microservice-ecommerce?schema=product_schema
# if DB_HOST environment variable use that otherwise use localhost instead

# by default eureka.client.enable= true then you dont need to use @EnableEurekaClient
# and also eureka.client.fetch-registry=true mean this client able to get data from eureka server
#and also eureka.client.register-with-eureka=true means this client able register to eureka server

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
