server:
  port: 8080
spring:
  application:
    name: PRODUCT-SERVICE

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  r2dbc:
    username: postgres
    password: MohammadN@sr13804804
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/microservice-ecommerce?schema=product_schema

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
