server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nasrmohammad4804/springboot-microservice.git
          search-paths:
            config-server/src/main/resources/config/
          clone-on-start: true
          default-label: master
