eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true


  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411/}

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 1500
        initial-interval: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'