eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 35
        max-interval: 1500
        initial-interval: 10000
